<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class ResourceSeeder extends Seeder
{
    public function run()
    {
        // 获取管理员用户作为默认创建者
        $admin = User::where('email', 'admin@study.com')->first();
        $adminId = $admin ? $admin->id : 1;

        $resources = [
            // 视频教程类
            [
                'title' => '尚硅谷前端技术栈全套教程',
                'description' => '包含HTML、CSS、JavaScript、Vue、React等前端开发全栈技术，适合初学者系统学习',
                'type' => 'video',
                'category' => 'Web开发',
                'difficulty' => 'beginner',
                'url' => 'https://www.bilibili.com/video/BV1Kg411T7t9',
                'duration' => 2400,
                'thumbnail' => 'https://i2.hdslb.com/bfs/archive/fe4c75e4a5e08b000e74a4e24999a0d50a9a18aa.jpg',
                'is_featured' => true,
                'view_count' => 158000,
                'download_count' => 0,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => '尚硅谷',
                'created_at' => '2024-01-01 10:00:00',
                'updated_at' => '2024-01-01 10:00:00'
            ],
            [
                'title' => '黑马程序员Java全套教程',
                'description' => 'Java零基础到就业，包含JavaSE、JavaWeb、框架、项目实战等完整体系',
                'type' => 'video',
                'category' => 'Java开发',
                'difficulty' => 'beginner',
                'url' => 'https://www.bilibili.com/video/BV1CV411F7dP',
                'duration' => 3600,
                'is_featured' => true,
                'view_count' => 245000,
                'download_count' => 0,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => '黑马程序员',
                'created_at' => '2024-01-02 10:00:00',
                'updated_at' => '2024-01-02 10:00:00'
            ],
            [
                'title' => 'Vue3 + TypeScript 企业级开发实战',
                'description' => '基于Vue3和TypeScript的现代前端开发，包含组合式API、Pinia状态管理等',
                'type' => 'video',
                'category' => 'Vue开发',
                'difficulty' => 'intermediate',
                'url' => 'https://www.bilibili.com/video/BV1dS4y1K7sH',
                'duration' => 1800,
                'is_featured' => true,
                'view_count' => 89000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => '技术胖',
                'created_at' => '2024-01-03 10:00:00',
                'updated_at' => '2024-01-03 10:00:00'
            ],
            [
                'title' => 'Python数据分析与机器学习',
                'description' => '从Python基础到数据分析，涵盖pandas、numpy、matplotlib、sklearn等库',
                'type' => 'video',
                'category' => 'Python',
                'difficulty' => 'intermediate',
                'url' => 'https://www.bilibili.com/video/BV1Ex411d7zK',
                'duration' => 2100,
                'view_count' => 76000,
                'rating' => 4.6,
                'creator_id' => $adminId,
                'creator_name' => '小甲鱼',
                'created_at' => '2024-01-04 10:00:00',
                'updated_at' => '2024-01-04 10:00:00'
            ],
            [
                'title' => 'React18 + TypeScript 开发教程',
                'description' => 'React18新特性详解，结合TypeScript进行企业级前端开发',
                'type' => 'video',
                'category' => 'React开发',
                'difficulty' => 'intermediate',
                'url' => 'https://www.bilibili.com/video/BV1dV4y1u7hJ',
                'duration' => 1500,
                'is_featured' => true,
                'view_count' => 125000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => '尚硅谷',
                'created_at' => '2024-01-21 10:00:00',
                'updated_at' => '2024-01-21 10:00:00'
            ],
            [
                'title' => 'Spring Cloud 微服务架构',
                'description' => 'Spring Cloud全家桶，构建微服务架构系统',
                'type' => 'video',
                'category' => 'Java开发',
                'difficulty' => 'advanced',
                'url' => 'https://www.bilibili.com/video/BV1M14y1k7qM',
                'duration' => 2800,
                'view_count' => 95000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => '黑马程序员',
                'created_at' => '2024-01-22 10:00:00',
                'updated_at' => '2024-01-22 10:00:00'
            ],
            [
                'title' => 'MySQL 数据库从入门到精通',
                'description' => '数据库基础、SQL语法、索引优化、性能调优完整教程',
                'type' => 'video',
                'category' => '数据库',
                'difficulty' => 'intermediate',
                'url' => 'https://www.bilibili.com/video/BV1kr4y1i7ru',
                'duration' => 3200,
                'is_featured' => true,
                'view_count' => 180000,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => '尚硅谷',
                'created_at' => '2024-01-23 10:00:00',
                'updated_at' => '2024-01-23 10:00:00'
            ],
            [
                'title' => 'Docker 容器技术教程',
                'description' => 'Docker容器化部署，从基础到实战项目应用',
                'type' => 'video',
                'category' => '运维部署',
                'difficulty' => 'intermediate',
                'url' => 'https://www.bilibili.com/video/BV1gr4y1U7CY',
                'duration' => 1800,
                'view_count' => 110000,
                'rating' => 4.6,
                'creator_id' => $adminId,
                'creator_name' => '狂神说Java',
                'created_at' => '2024-01-24 10:00:00',
                'updated_at' => '2024-01-24 10:00:00'
            ],

            // 文档资料类
            [
                'title' => 'Vue.js 官方中文文档',
                'description' => 'Vue.js框架的官方中文文档，包含完整的API参考和学习指南',
                'type' => 'document',
                'category' => 'Vue开发',
                'difficulty' => 'beginner',
                'url' => 'https://cn.vuejs.org/guide/',
                'is_featured' => true,
                'view_count' => 120000,
                'download_count' => 0,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => 'Vue.js官方',
                'created_at' => '2024-01-05 10:00:00',
                'updated_at' => '2024-01-05 10:00:00'
            ],
            [
                'title' => 'MDN Web 开发文档',
                'description' => 'Mozilla Developer Network提供的权威Web开发文档，涵盖HTML、CSS、JavaScript',
                'type' => 'document',
                'category' => 'Web开发',
                'difficulty' => 'beginner',
                'url' => 'https://developer.mozilla.org/zh-CN/',
                'is_featured' => true,
                'view_count' => 200000,
                'download_count' => 0,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => 'Mozilla',
                'created_at' => '2024-01-06 10:00:00',
                'updated_at' => '2024-01-06 10:00:00'
            ],
            [
                'title' => 'TypeScript 中文文档',
                'description' => 'TypeScript官方中文文档，学习TypeScript语法和高级特性',
                'type' => 'document',
                'category' => 'TypeScript',
                'difficulty' => 'intermediate',
                'url' => 'https://www.typescriptlang.org/zh/',
                'view_count' => 85000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'Microsoft',
                'created_at' => '2024-01-07 10:00:00',
                'updated_at' => '2024-01-07 10:00:00'
            ],
            [
                'title' => 'Spring Boot 官方文档',
                'description' => 'Spring Boot框架官方文档，包含配置、开发和部署指南',
                'type' => 'document',
                'category' => 'Java开发',
                'difficulty' => 'intermediate',
                'url' => 'https://spring.io/projects/spring-boot',
                'view_count' => 95000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => 'Spring',
                'created_at' => '2024-01-08 10:00:00',
                'updated_at' => '2024-01-08 10:00:00'
            ],
            [
                'title' => 'React 官方中文文档',
                'description' => 'React框架官方文档，学习组件化开发和状态管理',
                'type' => 'document',
                'category' => 'React开发',
                'difficulty' => 'beginner',
                'url' => 'https://react.docschina.org/',
                'is_featured' => true,
                'view_count' => 150000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'React官方',
                'created_at' => '2024-01-25 10:00:00',
                'updated_at' => '2024-01-25 10:00:00'
            ],
            [
                'title' => 'Vite 构建工具文档',
                'description' => '新一代前端构建工具，快速的开发体验',
                'type' => 'document',
                'category' => '构建工具',
                'difficulty' => 'intermediate',
                'url' => 'https://cn.vitejs.dev/',
                'view_count' => 85000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => 'Vite团队',
                'created_at' => '2024-01-26 10:00:00',
                'updated_at' => '2024-01-26 10:00:00'
            ],
            [
                'title' => 'Element Plus 组件库',
                'description' => '基于Vue3的桌面端组件库，提供丰富的UI组件',
                'type' => 'document',
                'category' => 'UI组件',
                'difficulty' => 'beginner',
                'url' => 'https://element-plus.org/zh-CN/',
                'view_count' => 200000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'Element团队',
                'created_at' => '2024-01-27 10:00:00',
                'updated_at' => '2024-01-27 10:00:00'
            ],

            // 在线链接类
            [
                'title' => 'LeetCode 算法题库',
                'description' => '全球知名的算法练习平台，提供大量编程题目和在线判题',
                'type' => 'link',
                'category' => '算法数据结构',
                'difficulty' => 'intermediate',
                'url' => 'https://leetcode.cn/',
                'is_featured' => true,
                'view_count' => 180000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'LeetCode',
                'created_at' => '2024-01-09 10:00:00',
                'updated_at' => '2024-01-09 10:00:00'
            ],
            [
                'title' => 'GitHub - 代码托管平台',
                'description' => '全球最大的代码托管平台，学习开源项目，参与开源贡献',
                'type' => 'link',
                'category' => '开发工具',
                'difficulty' => 'beginner',
                'url' => 'https://github.com/',
                'is_featured' => true,
                'view_count' => 500000,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => 'GitHub',
                'created_at' => '2024-01-10 10:00:00',
                'updated_at' => '2024-01-10 10:00:00'
            ],
            [
                'title' => 'CodePen - 在线代码编辑器',
                'description' => '前端代码在线编辑和分享平台，适合学习前端技术',
                'type' => 'link',
                'category' => 'Web开发',
                'difficulty' => 'beginner',
                'url' => 'https://codepen.io/',
                'view_count' => 120000,
                'rating' => 4.6,
                'creator_id' => $adminId,
                'creator_name' => 'CodePen',
                'created_at' => '2024-01-11 10:00:00',
                'updated_at' => '2024-01-11 10:00:00'
            ],
            [
                'title' => '掘金 - 技术社区',
                'description' => '中国领先的技术社区，分享技术文章和最新技术动态',
                'type' => 'link',
                'category' => '技术社区',
                'difficulty' => 'beginner',
                'url' => 'https://juejin.cn/',
                'view_count' => 300000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => '掘金',
                'created_at' => '2024-01-12 10:00:00',
                'updated_at' => '2024-01-12 10:00:00'
            ],
            [
                'title' => '牛客网 - 编程面试练习',
                'description' => '专注于编程面试的在线平台，算法题和面试经验分享',
                'type' => 'link',
                'category' => '算法数据结构',
                'difficulty' => 'intermediate',
                'url' => 'https://www.nowcoder.com/',
                'view_count' => 280000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => '牛客网',
                'created_at' => '2024-01-28 10:00:00',
                'updated_at' => '2024-01-28 10:00:00'
            ],
            [
                'title' => 'Stack Overflow 中文版',
                'description' => '程序员问答社区，解决编程技术问题',
                'type' => 'link',
                'category' => '技术社区',
                'difficulty' => 'beginner',
                'url' => 'https://stackoverflow.com/',
                'view_count' => 400000,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => 'Stack Overflow',
                'created_at' => '2024-01-29 10:00:00',
                'updated_at' => '2024-01-29 10:00:00'
            ],
            [
                'title' => 'Can I Use - 浏览器兼容性查询',
                'description' => '查询CSS、JS、HTML5等技术的浏览器支持情况',
                'type' => 'link',
                'category' => 'Web开发',
                'difficulty' => 'beginner',
                'url' => 'https://caniuse.com/',
                'view_count' => 150000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'Can I Use',
                'created_at' => '2024-01-30 10:00:00',
                'updated_at' => '2024-01-30 10:00:00'
            ],

            // 电子书籍类
            [
                'title' => 'JavaScript 高级程序设计（第4版）',
                'description' => '前端开发经典教材，深入讲解JavaScript语言特性和Web开发',
                'type' => 'book',
                'category' => 'JavaScript',
                'difficulty' => 'intermediate',
                'url' => 'https://www.ituring.com.cn/book/2472',
                'is_featured' => true,
                'view_count' => 85000,
                'download_count' => 12000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => '图灵教育',
                'created_at' => '2024-01-13 10:00:00',
                'updated_at' => '2024-01-13 10:00:00'
            ],
            [
                'title' => 'Java核心技术 卷I',
                'description' => 'Java开发经典教材，全面介绍Java语言核心特性',
                'type' => 'book',
                'category' => 'Java开发',
                'difficulty' => 'intermediate',
                'url' => 'https://book.douban.com/subject/26880667/',
                'view_count' => 95000,
                'download_count' => 15000,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => '机械工业出版社',
                'created_at' => '2024-01-14 10:00:00',
                'updated_at' => '2024-01-14 10:00:00'
            ],
            [
                'title' => '深入理解计算机系统（第3版）',
                'description' => '计算机系统经典教材，深入理解计算机工作原理',
                'type' => 'book',
                'category' => '计算机基础',
                'difficulty' => 'advanced',
                'url' => 'https://book.douban.com/subject/26912767/',
                'view_count' => 65000,
                'download_count' => 8000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => '机械工业出版社',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00'
            ],
            [
                'title' => 'Python编程：从入门到实践（第2版）',
                'description' => 'Python入门经典教材，从基础语法到项目实战',
                'type' => 'book',
                'category' => 'Python',
                'difficulty' => 'beginner',
                'url' => 'https://book.douban.com/subject/35196328/',
                'view_count' => 110000,
                'download_count' => 18000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => '人民邮电出版社',
                'created_at' => '2024-01-16 10:00:00',
                'updated_at' => '2024-01-16 10:00:00'
            ],
            [
                'title' => '算法导论（第3版）',
                'description' => '计算机算法经典教材，深入理解算法设计与分析',
                'type' => 'book',
                'category' => '算法数据结构',
                'difficulty' => 'advanced',
                'url' => 'https://book.douban.com/subject/20432061/',
                'view_count' => 85000,
                'download_count' => 10000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => '机械工业出版社',
                'created_at' => '2024-01-31 10:00:00',
                'updated_at' => '2024-01-31 10:00:00'
            ],
            [
                'title' => 'Vue.js 设计与实现',
                'description' => '深入Vue.js源码，理解框架设计原理和实现细节',
                'type' => 'book',
                'category' => 'Vue开发',
                'difficulty' => 'advanced',
                'url' => 'https://book.douban.com/subject/35768338/',
                'view_count' => 65000,
                'download_count' => 8000,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => '人民邮电出版社',
                'created_at' => '2024-02-01 10:00:00',
                'updated_at' => '2024-02-01 10:00:00'
            ],

            // 开发工具类
            [
                'title' => 'Visual Studio Code',
                'description' => '微软开发的免费代码编辑器，支持多种编程语言和丰富插件',
                'type' => 'tool',
                'category' => '开发工具',
                'difficulty' => 'beginner',
                'url' => 'https://code.visualstudio.com/',
                'is_featured' => true,
                'view_count' => 800000,
                'download_count' => 500000,
                'rating' => 4.9,
                'creator_id' => $adminId,
                'creator_name' => 'Microsoft',
                'created_at' => '2024-01-17 10:00:00',
                'updated_at' => '2024-01-17 10:00:00'
            ],
            [
                'title' => 'Git - 版本控制系统',
                'description' => '分布式版本控制系统，程序员必备工具',
                'type' => 'tool',
                'category' => '开发工具',
                'difficulty' => 'beginner',
                'url' => 'https://git-scm.com/',
                'is_featured' => true,
                'view_count' => 400000,
                'download_count' => 200000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'Git',
                'created_at' => '2024-01-18 10:00:00',
                'updated_at' => '2024-01-18 10:00:00'
            ],
            [
                'title' => 'Node.js 运行环境',
                'description' => '基于Chrome V8引擎的JavaScript运行环境，支持服务端开发',
                'type' => 'tool',
                'category' => 'Node.js',
                'difficulty' => 'intermediate',
                'url' => 'https://nodejs.org/',
                'view_count' => 300000,
                'download_count' => 150000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => 'Node.js',
                'created_at' => '2024-01-19 10:00:00',
                'updated_at' => '2024-01-19 10:00:00'
            ],
            [
                'title' => 'Postman API 测试工具',
                'description' => 'API开发和测试工具，支持REST、GraphQL等多种API格式',
                'type' => 'tool',
                'category' => '开发工具',
                'difficulty' => 'beginner',
                'url' => 'https://www.postman.com/',
                'view_count' => 250000,
                'download_count' => 100000,
                'rating' => 4.6,
                'creator_id' => $adminId,
                'creator_name' => 'Postman',
                'created_at' => '2024-01-20 10:00:00',
                'updated_at' => '2024-01-20 10:00:00'
            ],
            [
                'title' => 'WebStorm IDE',
                'description' => 'JetBrains出品的JavaScript开发IDE，智能代码编辑',
                'type' => 'tool',
                'category' => '开发工具',
                'difficulty' => 'beginner',
                'url' => 'https://www.jetbrains.com/webstorm/',
                'view_count' => 120000,
                'download_count' => 50000,
                'rating' => 4.7,
                'creator_id' => $adminId,
                'creator_name' => 'JetBrains',
                'created_at' => '2024-02-02 10:00:00',
                'updated_at' => '2024-02-02 10:00:00'
            ],
            [
                'title' => 'Figma 设计工具',
                'description' => '在线协作设计工具，UI/UX设计和原型制作',
                'type' => 'tool',
                'category' => '设计工具',
                'difficulty' => 'beginner',
                'url' => 'https://www.figma.com/',
                'view_count' => 180000,
                'download_count' => 80000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'Figma',
                'created_at' => '2024-02-03 10:00:00',
                'updated_at' => '2024-02-03 10:00:00'
            ],
            [
                'title' => 'Redis 数据库',
                'description' => '高性能的内存数据库，支持缓存、消息队列等场景',
                'type' => 'tool',
                'category' => '数据库',
                'difficulty' => 'intermediate',
                'url' => 'https://redis.io/',
                'view_count' => 140000,
                'download_count' => 60000,
                'rating' => 4.8,
                'creator_id' => $adminId,
                'creator_name' => 'Redis',
                'created_at' => '2024-02-04 10:00:00',
                'updated_at' => '2024-02-04 10:00:00'
            ]
        ];

        // 插入数据
        DB::table('resources')->insert($resources);
    }
} 